In [2]:
import pandas as pd
import numpy as np

Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})

In [3]:
Hut_Paradise_values = Hut_Paradise_DF.values

In [4]:
Hut_Paradise_values[4]

array([40, 33,  1,  6, 20, 16], dtype=int64)

In [5]:
Hut_Paradise_values[:,4]

array([ 8,  4,  5, 10, 20, 12,  5,  1, 10], dtype=int64)

In [6]:
Hut_Paradise_values[:,3]

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5], dtype=int64)

In [7]:
Hut_Paradise_values[:,1] - Hut_Paradise_values[:,5]

array([13, 12, 15, 13, 17,  9, 20, 15, 25], dtype=int64)

In [8]:
t = np.array([10,20,30,15,5,40,20,8,20])
L = np.dot(Hut_Paradise_values[:,4],t)
L

1348

In [9]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

In [10]:
a = 2*v - 3*w
a

array([-3, 14,  3,  4,  2])

In [11]:
np.dot(u, a)

0

In [12]:
A = np.array([
    [1, -5, 3], 
    [2, 2, 1],
    [0, 3, 1],
    [2, 4, 12]
])
A.shape

(4, 3)

5. Практика: базовые действия над матрицами

In [13]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

In [14]:
I = np.array([Husband_Income, Wife_Income, Mother_In_Law_Income])
C = np.array([Husband_Consumption, Wife_Consumption, Mother_In_Law_Consumption])

In [15]:
I = np.transpose(I)
C = np.transpose(C)

In [16]:
C

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

 Задание 5.3
1 point possible (graded)

Доходы представлены до уплаты налогов. Налоговая ставка — 13 %. Вычислите матрицу доходов семьи Ивановых после уплаты налогов.

In [17]:
I_T = 0.87 * I
I_T

array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])

In [18]:
P = I_T - C
P

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

7. Практика: матричное умножение

In [19]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

In [20]:
y = A@x
y

array([26, 30])

In [21]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

In [22]:
X = B@A

In [23]:
X

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

Задание 7.3 

In [24]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

In [25]:
A = np.array([x,y,z])

In [26]:
A

array([[ 1,  2,  1,  0,  4],
       [ 2,  1, -1,  1,  0],
       [-1,  1, -1,  0,  0]])

In [27]:
G = A.T@A

In [28]:
G

array([[ 6,  3,  0,  2,  4],
       [ 3,  6,  0,  1,  8],
       [ 0,  0,  3, -1,  4],
       [ 2,  1, -1,  1,  0],
       [ 4,  8,  4,  0, 16]])

In [29]:
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

адание 7.4
1 point possible (graded)

Найдите вектор прибыли салона по стилистам, если за каждую услугу стилисты платят салону определённую комиссию.

Вектор комиссий: com = np.array([0.2, 0.2, 0.3, 0.1, 0.1]).

In [30]:
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

In [31]:
A = Count_DF.values
B = Price_DF.values

In [32]:
A

array([[10,  5, 12, 15, 10],
       [ 2, 21,  3, 25,  6],
       [12, 12,  0, 30,  4],
       [ 4,  8, 18, 14,  5],
       [ 6, 25, 27, 25, 18],
       [10,  3,  2, 17, 12],
       [22,  1,  4, 25, 20],
       [ 7,  0, 31, 31, 28]], dtype=int64)

In [33]:
B

array([[2. , 1.5, 1. , 0.8, 1. ],
       [1.8, 2.5, 1. , 1. , 1. ],
       [2. , 2. , 0. , 0.5, 2. ],
       [1.8, 1.2, 2.8, 0.8, 2. ],
       [2.5, 3.5, 2. , 1. , 1.5],
       [5. , 5. , 3. , 2. , 2.5],
       [1.1, 1. , 1.5, 0.5, 1.7],
       [4.5, 4. , 2.5, 1. , 2. ]])

In [34]:
Money = A * B
Money

array([[20. ,  7.5, 12. , 12. , 10. ],
       [ 3.6, 52.5,  3. , 25. ,  6. ],
       [24. , 24. ,  0. , 15. ,  8. ],
       [ 7.2,  9.6, 50.4, 11.2, 10. ],
       [15. , 87.5, 54. , 25. , 27. ],
       [50. , 15. ,  6. , 34. , 30. ],
       [24.2,  1. ,  6. , 12.5, 34. ],
       [31.5,  0. , 77.5, 31. , 56. ]])

In [35]:
Inc = Money@com
Inc

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

In [36]:
St = Money@(1 - com)
St

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

In [37]:
A = np.matrix('2,0,0; 0,4,0; 0,0,5')
A

matrix([[2, 0, 0],
        [0, 4, 0],
        [0, 0, 5]])

In [38]:
B = np.linalg.inv(A)
B

matrix([[0.5 , 0.  , 0.  ],
        [0.  , 0.25, 0.  ],
        [0.  , 0.  , 0.2 ]])

In [39]:
A = np.matrix ("1, 2, 3; 4, 5, 6 ; 7, 8, 10")
print(np.linalg.det(A))
# -3.0000000000009

-2.9999999999999996


In [40]:
A = np.matrix('1,2; 1,1')
B = np.matrix('5,-2; -1,4')
print(np.linalg.det(A))

-1.0


In [41]:
A+B

matrix([[6, 0],
        [0, 5]])

In [42]:
print(np.linalg.det(A+B))

29.99999999999999


In [43]:
import numpy as np
v1 = np.array([1,2,3,1])
v2 = np.array([4,5,6,1])
v3 = np.array([7,8,9,1])
A = np.array([v1, v2, v3]).T
print(np.linalg.matrix_rank(A))
# 2

2


10. Практика: обратная матрица, определитель, ранг

Задание 10.1 

In [44]:
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])

In [45]:
B = np.linalg.inv(A)
B

array([[-1.875  ,  2.3125 , -0.03125],
       [ 0.375  , -0.5625 ,  0.15625],
       [ 1.25   , -1.375  , -0.0625 ]])

Задание 10.2 

In [46]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

In [47]:
A = np.matrix([v1,v2,v3,v4]).T
print('Ранг матрицы: ', np.linalg.matrix_rank(A))

Ранг матрицы:  4


Задание 10.4 

In [48]:
G = A.T@A
G

matrix([[360,  96,  73, -35],
        [ 96,  46,  16,   4],
        [ 73,  16,  33,   4],
        [-35,   4,   4,  51]])

In [49]:
d = np.linalg.det(A.T@A)
round(d)

3716648

In [50]:
G_ = np.linalg.inv(G)
round(G_[2,0],3)

-0.026

In [51]:
G_

matrix([[ 0.01711488, -0.02798543, -0.02623063,  0.01599775],
        [-0.02798543,  0.071967  ,  0.03031441, -0.02722776],
        [-0.02623063,  0.03031441,  0.07683106, -0.02640498],
        [ 0.01599775, -0.02722776, -0.02640498,  0.03479318]])

In [52]:
A = np.matrix([[1,1],[1,2]])
G = A.T@A
G

matrix([[2, 3],
        [3, 5]])

In [53]:
A = np.matrix([[1,2],[3,7]])
A = np.linalg.inv(A)
A

matrix([[ 7., -2.],
        [-3.,  1.]])

In [54]:
v1 = np.array([2,10,-2])
v2 = np.array([3,2,-2])
v3 = np.array([8,14,-6])
A = np.matrix([v1,v2,v3])
r = np.linalg.matrix_rank(A)
r

2

In [55]:
D = np.linalg.det(A)
D

0.0

In [56]:
v1 = np.array([4,7,-1,7])
v2 = np.array([-4,2,5,3])
v3 = np.array([0,9,4,10])
A = np.matrix([v1,v2,v3])
r = np.linalg.matrix_rank(A)
r

2

In [57]:
A = np.matrix([[1,2],[-3,1],[1,2],[1,-1]])
G = A.T@A
G

matrix([[12,  0],
        [ 0, 10]])

In [58]:
G_ = np.linalg.inv(G)
G_

matrix([[0.08333333, 0.        ],
        [0.        , 0.1       ]])

In [59]:
a = A.T @ np.array([1,4,5,0])
a

matrix([[-6, 16]])

In [60]:
w = G_ @ np.array([-6,16])
w

matrix([[-0.5,  1.6]])

In [61]:
import time

def timing_decorator(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        print(f"Function {func.__name__} took {end_time - start_time} seconds to run.")
        return result
    return wrapper

In [62]:
@timing_decorator
def my_function():
    # some code here
    time.sleep(1)  # simulate some time-consuming operation
    return

In [63]:
my_function()

Function my_function took 1.0003182888031006 seconds to run.


In [64]:
x_1 = np.array([5, 1, 2])
x_2 = np.array([4, 2, 8])
np.corrcoef(x_1, x_2)

array([[1.        , 0.05241424],
       [0.05241424, 1.        ]])

In [65]:
x_1 = np.array([5.1, 1.8, 2.1, 10.3, 12.1, 12.6])
x_2 = np.array([10.2, 3.7, 4.1, 20.5, 24.2, 24.1])
x_3 = np.array([2.5, 0.9, 1.1, 5.1, 6.1, 6.3])
A = np.corrcoef([x_1, x_2, x_3])
print('rank ', np.linalg.matrix_rank(A))
print('det ', round(np.linalg.det(A),7))

rank  3
det  5e-07


In [66]:
y = 10.4 + 8*1 + 0.5*4 + 3*1 + 0.4*16
y

29.799999999999997

In [67]:
A = np.array([
    [1, 3, -2, 9]
]).T
y = np.array([
    3, 7, -5, 21
])

In [68]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=2, include_bias=True)
A_poly = poly.fit_transform(A)
display(pd.DataFrame(A_poly))

0    1     2
0  1.0  1.0   1.0
1  1.0  3.0   9.0
2  1.0 -2.0   4.0
3  1.0  9.0  81.0

In [69]:
y

array([ 3,  7, -5, 21])

In [70]:
A_poly.T@A_poly

array([[4.000e+00, 1.100e+01, 9.500e+01],
       [1.100e+01, 9.500e+01, 7.490e+02],
       [9.500e+01, 7.490e+02, 6.659e+03]])

In [71]:
np.linalg.inv(A_poly.T@A_poly)@A_poly.T

array([[ 0.36417398,  0.30866082,  0.38496757, -0.05780237],
       [ 0.07188732,  0.17582348, -0.23909449, -0.0086163 ],
       [-0.01313112, -0.02282844,  0.02200178,  0.01395778]])

In [72]:
w_hat = np.linalg.inv(A_poly.T@A_poly)@A_poly.T@y
print(round(w_hat[0],1))
print(round(w_hat[1],1))
print(round(w_hat[2],1))

0.1
2.5
-0.0


7. Регуляризация

In [73]:
from sklearn.model_selection import cross_validate
from sklearn.linear_model import LinearRegression

In [74]:
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'PRICE']
boston_data = pd.read_csv('data/housing.csv', header=None, delimiter=r"\s+", names=column_names)
boston_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  PRICE  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2

In [75]:
# выделяем интересующие нас факторы
X = boston_data[['LSTAT', 'PTRATIO', 'RM','CRIM']]
y = boston_data[['PRICE']]
 
# добавляем полиномиальные признаки
poly = PolynomialFeatures(degree=2, include_bias=False)
X = poly.fit_transform(X)
 
# создаём модель линейной регрессии
lr = LinearRegression()
 
# оцениваем качество модели на кросс-валидации, метрика — MAPE
cv_results = cross_validate(lr, X, y, scoring='neg_mean_absolute_percentage_error', cv=5, return_train_score=True)
print('MAPE на тренировочных фолдах: {:.2f} %'.format(-cv_results['train_score'].mean()* 100))
print('MAPE на валидационных фолдах: {:.2f} %'.format(-cv_results['test_score'].mean() * 100))	

MAPE на тренировочных фолдах: 13.47 %
MAPE на валидационных фолдах: 17.34 %


In [79]:
A = np.array([
    [1, 1, 1, 1, 1],
    [5, 9, 4, 3, 5],
    [15, 18, 18, 19, 19],
    [7, 6, 7, 7, 7]
]).T
y = np.array([24, 22, 35, 33, 36])
A


array([[ 1,  5, 15,  7],
       [ 1,  9, 18,  6],
       [ 1,  4, 18,  7],
       [ 1,  3, 19,  7],
       [ 1,  5, 19,  7]])

In [88]:
w = np.linalg.inv(A.T@A + np.eye(4))@A.T@y
w = np.round(w,2)
w

array([-0.09, -1.71,  1.91,  0.73])

In [89]:
A = np.array([
    [1, 1, 1, 1, 1],
    [5, 9, 4, 3, 5],
    [15, 18, 18, 19, 19],
    [7, 6, 7, 7, 7]
]).T
y = np.array([24, 22, 35, 33, 36])
E = np.eye(4)
# коэффициент регуляризации
alpha = 1
# получаем оценку коэффициентов регрессии по МНК с регуляризацией Тихонова
w_hat_ridge = np.linalg.inv(A.T@A+alpha*E)@A.T@y
print(np.round(w_hat_ridge, 2))

[-0.09 -1.71  1.91  0.73]
