In [22]:
import numpy as np

In [23]:
# создаем матрицу А
A = np.array([
    [3, 1],
    [2, 2]
]).T
# вычисляем собственные числа и собственные векторы
eig_values, eig_vectors = np.linalg.eig(A)
print('Собственные числа: \n', eig_values)
print('Собственные векторы: \n', eig_vectors)

Собственные числа: 
 [4. 1.]
Собственные векторы: 
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [24]:
# создаем матрицу А
A = np.array([
    [1, 105],
    [105, 1]
]).T
# вычисляем собственные числа и собственные векторы
eig_values, eig_vectors = np.linalg.eig(A)
print('Собственные числа: \n', eig_values)
print('Собственные векторы: \n', eig_vectors)

Собственные числа: 
 [ 106. -104.]
Собственные векторы: 
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [25]:
A

array([[  1, 105],
       [105,   1]])

 Задание 4.1
3 points possible (ungraded)

Найдите собственные числа для матрицы:

In [26]:
# создаем матрицу А
A = np.array([
    [1, 3, 5],
    [4, -4, 9],
    [13, 7, 12]
]).T
# вычисляем собственные числа и собственные векторы
eig_values, eig_vectors = np.linalg.eig(A)
print('Собственные числа: \n', np.round(eig_values))
print('Собственные векторы: \n', eig_vectors)

Собственные числа: 
 [20. -4. -7.]
Собственные векторы: 
 [[-0.59065136 -0.9084069  -0.40394124]
 [-0.29844178 -0.16657961 -0.77823322]
 [-0.74970893  0.38346857  0.48081652]]


In [27]:
# создаем матрицу А
A = np.array([
    [1, 9, 4],
    [9, 4, 7],
    [4, 7, 12]
]).T
G = A.T@A
# вычисляем собственные числа и собственные векторы
eig_values, eig_vectors = np.linalg.eig(G)
print('Собственные числа: \n', np.round(eig_values))
print('Собственные векторы: \n', eig_vectors)

Собственные числа: 
 [391.  46.  16.]
Собственные векторы: 
 [[-0.41955589 -0.7323045  -0.5363795 ]
 [-0.55709648  0.67425896 -0.48478693]
 [-0.71667034 -0.09541992  0.69085358]]


In [28]:
# создаем матрицу А
A = np.array([
    [12, 6],
    [6, 12]
]).T
# вычисляем собственные числа и собственные векторы
eig_values, eig_vectors = np.linalg.eig(A)
print('Собственные числа: \n', np.round(eig_values))
print('Собственные векторы: \n', eig_vectors)

Собственные числа: 
 [18.  6.]
Собственные векторы: 
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [29]:
# создаем матрицу А
A = np.array([
    [6, -2],
    [-2, -480]
]).T
np.linalg.det(np.matrix(A))

-2884.0000000000014

In [30]:
A

array([[   6,   -2],
       [  -2, -480]])

In [31]:
(-30 * (2 ** 4) * 6) - 4

-2884

 6. Метод главных компонент

Задание 6.5

In [34]:
# создаем матрицу А
A = np.array([
    [1, 0.9922],
    [0.9922, 1]
]).T
np.linalg.det(np.matrix(A))
# вычисляем собственные числа и собственные векторы
eig_values, eig_vectors = np.linalg.eig(A)
print('Собственные числа: \n', np.round(eig_values))
print('Собственные векторы: \n', eig_vectors)

Собственные числа: 
 [2. 0.]
Собственные векторы: 
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [37]:
x1 = np.array([1,2,1,1]).T

In [40]:
x1 = A[1,1] * 1 - A[1,1] * 70
x1

-69.0