# Игра угадай число

## Угадываем методом деления интервала, менее чем за 20 попыток

In [30]:
from game_v2 import score_game, predict_number_less20
score_game(predict_number_less20)

Наш алгоритм угадывает число в среднем за:5 попыток


5

Numpy library

In [40]:
import numpy as np
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)

nd_arr.shape
# 2


(3, 3)

In [106]:
np.iinfo(np.uint8)


iinfo(min=0, max=255, dtype=uint8)

In [87]:
import numpy as np

def shuffle_seed(array):
    s = np.random.randint(2**32 - 1, dtype = np.uint64)
    np.random.seed(s)
    new_array = np.random.permutation(array)
    return (new_array, s)
    
array = [1, 2, 3, 4, 5]
shuffle_seed(array)
# (array([1, 3, 2, 4, 5]), 2332342819)
shuffle_seed(array)
# (array([4, 5, 2, 3, 1]), 4155165971)

(array([1, 2, 4, 5, 3]), 3856567163)

In [96]:
import numpy as np

def min_max_dist(*vectors):

    vector_ = None
    distance_list = []
    for i in range(len(vectors)):
        for j in range(i + 1, len(vectors)):
            distance = np.linalg.norm(vectors[j] - vectors[i])
            distance_list.append(distance)

    return (min(distance_list), max(distance_list))            
    # Напишите тело функции

vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])
 
min_max_dist(vec1, vec2, vec3)

5.196152422706632
10.392304845413264


In [99]:
import numpy as np

def any_normal(*vectors):

    vector_ = None
    distance_list = []
    for i in range(len(vectors)):
        for j in range(i + 1, len(vectors)):
            if np.dot(vectors[j], vectors[i]) == 0:
                return True
    return False
    # Напишите тело функции

vec1 = np.array([2, 1])
vec2 = np.array([-1, 2])
vec3 = np.array([3,4])
 
any_normal(vec1, vec2, vec3)

True

In [111]:
import numpy as np

def get_unique_loto(num):
    loto_arr = np.zeros((num,5,5), dtype=np.uint8)
    my_array = range(1, 101)
    print(my_array)
    for i in range(num):
        loto_arr[i] = np.random.choice(my_array, size=(5,5), replace=False)
    return loto_arr

get_unique_loto(3)


range(1, 101)


array([[[56, 86, 39, 33, 95],
        [54, 80, 64,  8, 62],
        [ 9, 43, 46,  3, 11],
        [30, 91, 50, 90, 26],
        [96, 41, 58, 21,  4]],

       [[73, 60, 98, 45, 25],
        [16, 22, 53, 24, 92],
        [55, 68, 80, 33, 67],
        [77, 36,  3, 97, 62],
        [28, 44,  9, 21, 58]],

       [[49, 46,  1, 71,  2],
        [36, 73, 31, 98, 51],
        [41, 28, 26, 42, 20],
        [33, 99, 11, 45, 94],
        [17, 10, 82, 59, 14]]], dtype=uint8)

In [112]:
import numpy as np
simplelist = [19, 242, 14, 152, 142, 1000]
np.mean(simplelist)

261.5